# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will download a prebuilt Ruby version, install dependencies and run tests with Rake
# For more information see: https://github.com/marketplace/actions/setup-ruby-jruby-and-truffleruby

name: Rails CI/CD

on:
  push:
    branches: [ master, staging ]
  pull_request:
    branches: [ staging ]
  workflow_dispatch:
    inputs:
      tags:
        description: "Don't mind"
        required: false
        type: boolean
        default: false

jobs:
  rubocop:
    name: Run rubocop autofix
    runs-on: ubuntu-latest
    steps:
      - name: Checkout (pull request)
        if: github.event_name == 'pull_request'
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.ref }}
      - name: Checkout (push)
        if: github.event_name != 'pull_request'
        uses: actions/checkout@v2
      - name: Set up Ruby (Org API)
        uses: ruby/setup-ruby@v1.101.0
      - name: Run rubocop
        uses: Vinccool96/rubocop-linter@feature/migrate_to_node
      - name: Add & Commit
        uses: EndBug/add-and-commit@v9.0.0
        with:
          message: 'rubocop-linter commit'